rules = {
    #Groceries
    'Lidl': ('Groceries', 'Lidl'),
    'Kaufland': ('Groceries', 'Kaufland'),
    'BioTechUSA': ('Groceries', 'Misc'),
    'BioTech USA': ('Groceries', 'Misc'),
    'Biotech Usa': ('Groceries', 'Misc'),
    'Kraj': ('Groceries', 'Kraj'),
    'Yeme': ('Groceries', 'Yeme'),
    'BILLA': ('Groceries', 'Billa'),
    'Tesco': ('Groceries', 'Tesco'),
    'Potraviny Malina': ('Groceries', 'Malina'),
    'Terno': ('Groceries', 'Terno'),
    'Farm House EU': ('Groceries', 'Misc'),
    'Konzum': ('Groceries', 'Konzum'),
    'Asian Shop': ('Groceries', 'Misc'),
    'Edys Food S.r.o.': ('Groceries', 'Misc'),
    'Minimart': ('Groceries', 'Misc'),
    'Spar': ('Groceries', 'Spar'),
    'Studenac': ('Groceries', 'Studenac'),
    'Absolute': ('Groceries', 'Misc'),
    'Local Store': ('Groceries', 'Misc'),
    'Dufry': ('Groceries', 'Misc'),
    'RELAY': ('Groceries', 'Misc'),
    'Very Goodies': ('Groceries', 'Misc'),
    'Mini Potraviny Stanica': ('Groceries', 'Misc'),
    'Shell': ('Groceries', 'Misc'),
    'Snacks Cold Drinks': ('Groceries', 'Misc'),
    'OMV': ('Groceries', 'Misc'),
    'Grain Home Bakery': ('Groceries', 'Misc'),
    'Start Gd Ood': ('Groceries', 'Misc'),
    'Fantastico': ('Groceries', 'Misc'),
    #Alza
    'Alza': ('Alza', 'Alza'),
    #Clothes
    'Peek & Cloppenburg': ('Clothes', 'Clothes'),
    'ZARA': ('Clothes', 'Clothes'),
    #Topups
    'Apple Pay Top-Up by': ('Domino', 'Domino'),
    'From MARGARITA PLAMENOVA PARVANOVA': ('Maggie', 'Maggie'),
    #Drogerie
    'dm drogerie': ('Drogerie', 'DM'),
    '101 Drogerie': ('Drogerie', '101 Drogerie'),
    'Notino': ('Drogerie', 'Notino'),
    'bioruze.cz': ('Drogerie', 'Misc'),
    'Notino': ('Drogerie', 'Notino'),
    'TETA drogerie': ('Drogerie', 'TETA'),
    'Ptd 267': ('Drogerie', 'Misc'),
    #Entertainment
    'YouTube': ('Entertainment', 'subscriptions'),
    'Cinema City': ('Drogerie', 'cinema'),
    'Disney+': ('Entertainment', 'subscriptions'),
    'CINEMAX': ('Entertainment', 'cinema'),
    'Cafe Bar Leader Frui': ('Entertainment', 'meeting strangers'),
    'Wings Of Nature S.r.o.': ('Entertainment', 'trip to Devin'),
    'Albi': ('Entertainment', 'gift'),
    'Ticketportal': ('Entertainment', 'concert tickets'),
    'Ticketmaster': ('Entertainment', 'concert tickets'),
    'Martinus': ('Entertainment', 'gift'),
    'Predeti.sk': ('Entertainment', 'gift'),
    'ILLUI': ('Entertainment', 'gift'),
    'Manufaktura Sc Cent': ('Entertainment', 'gift'),
    'Billiard club Lavos': ('Entertainment', 'billiard'),
    'High Street Club Ba': ('Entertainment', 'kpop'),
    'Ip643001': ('Entertainment', 'dance'),
    'Slovak Gifts & Goods': ('Entertainment', 'gift'),
    'Decathlon': ('Entertainment', 'Sport Stuff'),
    'Welcome Trading Airport V': ('Entertainment', 'gift'),
    'Flowers Design Eood': ('Entertainment', 'gift'),
    'Adventured Shop Sk': ('Entertainment', 'gift'),
    'Sports Direct': ('Entertainment', 'Sport Stuff'),
    'Å evt': ('Entertainment', 'misc'),
    'Ševt': ('Entertainment', 'misc'),   
    'Home & You': ('Entertainment', 'gift'),
    'ReMax Courier Service': ('Entertainment', 'fun toy wink wink'),
    'Vivo': ('Entertainment', 'Misc'),
    'Fusakle Vivo': ('Entertainment', 'gift'),
    #Health
    'Dr.Max': ('Health', 'medicine'),
    'Benu lekáreň': ('Health', 'medicine'),
    'Naše Lekárne': ('Health', 'medicine'),
    'Benu lekÃ¡reÅˆ': ('Health', 'medicine'),
    'Digifiks': ('Health', 'medicine'),
    'VaÅ¡a lekÃ¡reÅˆ': ('Health', 'medicine'),
    'NaÅ¡e LekÃ¡rne': ('Health', 'medicine'),
    'Ljekarne KriÅ¡to': ('Health', 'medicine'),
    'Jadran Ljekarna': ('Health', 'medicine'),
    'EMPÃRIA SLOVAKIA': ('Health', 'medicine'),
    #Home
    'IKEA': ('Home', 'IKEA'),
    'Adel Design Ba Ivan.c.': ('Home', 'Misc'),
    'Vianocna Predajna': ('Home', 'Xmas'),
    'CEWE Fotolab': ('Home', 'printing'),
    'D222 Gls': ('Home', 'vacuum hose'),
    'JYSK': ('Home', 'JYSK'),
    'Tescoma': ('Home', 'Kitchen'),
    'Orion': ('Home', 'Kitchen'),
    'DATART': ('Home', 'Electronics'),
    'HORNBACH': ('Home', 'HORNBACH'),
    #Pet
    'Zoohit': ('Pet', 'Food/Sand'),
    'Super zoo': ('Pet', 'Food/Sand'),
    'Pet center': ('Pet', 'Food/Sand'),
    'Super Zoo Veterina S.': ('Pet', 'Vet'),
    'Knowhau': ('Pet', 'Vet'),
    #Takeout
    'Bolt Food': ('takeout','Bolt'),
    '"agentura Ges" Ke': ('takeout','takeout'),
    '100 grama sladki': ('takeout','takeout'),
    '100 Karaoke Ba Kamenne N': ('takeout','drinks'),
    '100karaoke Sro Ba Vysoka': ('takeout','drinks'),
    '718 Ood': ('takeout','restaurant'),
    'Ahoy Cafe': ('takeout','café'),
    'Anker': ('takeout','café'),
    'APIM Gastro': ('takeout','takeout'),
    'Apollo Lights & Sound S.r': ('takeout','takeout'),
    'Art Vox': ('takeout','takeout'),
    'Big Daddy': ('takeout','restaurant'),
    'Bistro': ('takeout','Bistro'),
    'BISTRO': ('takeout','Bistro'),    
    'Bistro.sk': ('takeout','Bistro'),
    'Bloom Bakery Nivy': ('takeout','café'),
    'Bram Bar': ('takeout','drinks'),
    'Petržalka Bowling Center': ('takeout','drinks'),
    'Bruschetta Restaurant': ('takeout','restaurant'),
    'Bufet Pod Schodami Tn': ('takeout','takeout'),
    'Capo': ('takeout','restaurant'),
    'Crēpes De Luxe': ('takeout','restaurant'),
    'Chilantro': ('takeout','Mall'),
    'Christmas Market': ('takeout','xmas market'),
    'Cidaris D.o.o.': ('takeout','restaurant'),
    'Coffee & Cake Centar': ('takeout','café'),
    'Costa Coffee': ('takeout','café'),
    'Crepes De Luxe': ('takeout','restaurant'),
    'Dir Fast Food': ('takeout','takeout'),
    'Doraemon Tea': ('takeout','takeout'),
    'Dpmb Br': ('takeout','takeout'),
    'Dubravska Pivaren 2': ('takeout','takeout'),
    'Eissalon Bortolotti': ('takeout','takeout'),
    'Familiya': ('takeout','takeout'),
    'Fruitisimo': ('takeout','Smoothie'),
    'Gatto Matto': ('takeout','restaurant'),
    'Glacio': ('takeout','Ice cream'),
    'I love pasta': ('takeout','restaurant'),
    'KÃ¡vomaty': ('takeout','takeout'),
    'Karma': ('takeout','takeout'),
    'Kaviaren Cafesta': ('takeout','café'),
    'Kaviaren Hrad': ('takeout','café'),
    'KFC': ('takeout','takeout'),
    'KlubovÅˆa': ('takeout','restaurant'),
    'Koliba Pod Vlkolincom': ('takeout','restaurant'),
    'Kolkovna': ('takeout','restaurant'),
    'Kontajner Coffee & Food Bar': ('takeout','café'),
    'La Donuteria': ('takeout','takeout'),
    'Lomada S. R. O.': ('takeout','takeout'),
    'Lucky Grill': ('takeout','xmas market'),
    'Luculus Ice': ('takeout','Ice cream'),
    'Ludmila Vaskovicova': ('takeout','takeout'),
    'Mama Mia': ('takeout','takeout'),
    'MarÃ­na': ('takeout','takeout'),
    'Marian Kosina': ('takeout','takeout'),
    "McDonald's": ('takeout','takeout'),
    'Memento': ('takeout','takeout'),
    'Minies 2': ('takeout','takeout'),
    'Minigolf Å trkovec': ('takeout','restaurant'),
    'Nc87 Banivy': ('takeout','takeout'),
    'NP Patisserie': ('takeout','takeout'),
    'Old Brick Pub': ('takeout','restaurant'),
    'PÃ¡n Cakes': ('takeout','restaurant'),
    'Panini Grup Ood': ('takeout','takeout'),
    'Papa Turkish': ('takeout','takeout'),
    'Pbz84kantuna': ('takeout','restaurant'),
    'Pekaren Naglreiter Fre': ('takeout','takeout'),
    'PetrÅ¾alka Bowling Center': ('takeout','drinks'),
    'Planetka Restaurant&Bar': ('takeout','takeout'),
    'Pletenica Polsovnica P': ('takeout','takeout'),
    'PNSKA': ('takeout','takeout'),
    'Primi River Lounge': ('takeout','takeout'),
    'Rb10': ('takeout','takeout'),
    'Restauracia Loparik': ('takeout','restaurant'),
    'Restauracia Pod Hradom': ('takeout','restaurant'),
    'Restaurant': ('takeout','restaurant'),
    'PNRetro RistoranteSKA': ('takeout','restaurant'),
    'Ristorante Piazza': ('takeout','restaurant'),
    'PNSKA': ('takeout','restaurant'),
    'Rk4': ('takeout','takeout'),
    'PNSKA': ('takeout','restaurant'),
    'Roxor': ('takeout','restaurant'),
    'Saint Coffee': ('takeout','café'),
    'Sinep S. R. O.': ('takeout','restaurant'),
    'Slatka Tajna 2': ('takeout','restaurant'),
    'Snack Bar Sunset': ('takeout','restaurant'),
    'Sova Caffe': ('takeout','café'),
    'Speranza': ('takeout','restaurant'),
    'Subway': ('takeout','takeout'),
    'The International': ('takeout','drinks'),
    'Tout Ba Mierova': ('takeout','café'),
    'U NÃS NA LIPTOVE': ('takeout','restaurant'),
    'Vespa Caffetteria Park': ('takeout','café'),
    'Voxar': ('takeout','takeout'),
    'Wiener Linien': ('takeout','takeout'),
    'Wild Thing Karaoke': ('takeout','drinks'),
    'Wok & Sushi restaurant Panda': ('takeout','restaurant'),
    'Wolt': ('takeout','Wolt'),
    'X Akcie': ('takeout','takeout'),
    #Travel
    'Ã–BB': ('travel','Zadar'),
    'Å½elezniÄnÃ¡ spoloÄnosÅ¥ Slovensko - Å½SSK': ('travel','Kosice/Travel around Slovakia'),
    'Železničná spoločnosť Slovensko - ŽSSK': ('travel','Kosice/Travel around Slovakia'),
    'Airbnb': ('travel','Airbnb'),
    "Bill's": ('travel','fuckin London'),
    'Blaguss Slovakia Sro': ('travel','travel'),
    'BratislavskÃ¡ integrovanÃ¡ doprava (BID)': ('travel','travel'),
    'British Museum': ('travel','fuckin London'),
    'Brno iD': ('travel','Brno'),
    'CH&CO': ('travel','fuckin London'),
    'Cheeky Scone': ('travel','fuckin London'),
    'Ci Tua': ('travel','fuckin London'),
    'Dominion Theatre': ('travel','fuckin London'),
    'DopravnÃ½ podnik Bratislava - DPB': ('travel','travel'),
    'Eurobus As': ('travel','travel'),
    'FlixBus': ('travel','FlixBus'),
    'Granger': ('travel','fuckin London'),
    'Hampton Court Palace': ('travel','fuckin London'),
    'Headout': ('travel','fuckin London'),
    'HMSHost International': ('travel','fuckin London'),
    'Ic2': ('travel','Kosice/Travel around Slovakia'),
    'Ic3': ('travel','Kosice/Travel around Slovakia'),
    'Ids Bbsk': ('travel','travel'),
    'Local Store': ('travel','fuckin London'),
    'My Old Dutch': ('travel','fuckin London'),
    'Natural History Museum': ('travel','fuckin London'),
    'Nikthenuts': ('travel','fuckin London'),
    'Paddington Station': ('travel','fuckin London'),
    'Patty & Bun': ('travel','fuckin London'),
    'Portobello': ('travel','fuckin London'),
    'Rk5': ('travel','Kosice/Travel around Slovakia'),
    'Royal Sweet Cafe': ('travel','fuckin London'),
    'Ryanair': ('travel','Plane tickets'),
    'Slovak Lines': ('travel','travel'),
    'Sky Garden': ('travel','fuckin London'),
    'T O T A L C H I': ('travel','fuckin London'),
    'Trenciansky Hrad M': ('travel','travel'),
    'Tst Sunday In Brooklyn': ('travel','fuckin London'),
    'Urban Fine Art Lt': ('travel','fuckin London'),
    'WHSmith': ('travel','fuckin London'),
    'World Duty Free': ('travel','fuckin London'),
    #Cash
    'Cash at ': ('Cash','ATM'),
    'Revolut Ltd': ('Cash','Sending money'),
    'To NIKOLAS PETRUSKA': ('Cash','Sending money'),
    'To Ivan M': ('Cash','Sending money'),
    'To MAREK MGR JELEMENSKY': ('Cash','Sending money'),
    #Taxi
    'Bolt': ('Taxi','Bolt'),
    

   




























}
